[book]
authors = ["JYU"]
language = "fi"
src = "src"
title = "Ohjelmointi 2"

[build]
create-missing = false

[output.html]
site-url = "/ohj2/"
edit-url-template = "https://github.com/ohj-perus-jy/ohj2/edit/main/{path}"
additional-css = [
  "highlight/atelier-forest-light.css",
  "highlight/twilight.css", 
  "highlight/apprentice.css",
  "theme/alerts-style.css",
  "theme/accordion.css",
  "theme/codeblock-tabs.css",
  "theme/code-highlights.css",
  "theme/tasks.css",
  "theme/asciinema-player.css",
]
default-theme = "jyu-light"
preferred-dark-theme = "jyu-dark"
additional-js = [
  "mermaid/mermaid.min.js", 
  "mermaid/mermaid-init.js",
  "theme/mode-java.js",
  "theme/playground_ext.js",
  "theme/accordion.js",
  "theme/codeblock-tabs.js",
  "theme/code-highlights.js",
  "theme/asciinema-player.min.js",
  "theme/asciinema-component.js",
]

[output.html.playground]
editable = true

[output.html.code.hidelines]
java = "//-"
javascript = "//-"

[preprocessor.alerts]

[preprocessor.mermaid]

[preprocessor.katex]

[preprocessor.codeblock-tabs]

[preprocessor.accordion]
command = "python3 ./preprocessors/python/accordion.py"

[preprocessor.plantuml]
plantuml-cmd="https://www.plantuml.com/plantuml"

[preprocessor.inline-highlighting]