[book]
authors = ["JYU"]
language = "fi"
src = "src"
title = "Ohjelmointi 2"

[output.html]
additional-css = [
  "highlight/atelier-forest-light.css",
  "highlight/twilight.css", 
  "highlight/apprentice.css", 
]
default-theme = "jyu-light"
preferred-dark-theme = "jyu-dark"
additional-js = [
  "mermaid/mermaid.min.js", 
  "mermaid/mermaid-init.js",
  "theme/mode-java.js",
  "theme/playground_ext.js",
]

[output.html.playground]
editable = true

[preprocessor.alerts]

[preprocessor.mermaid]